language: php

sudo: true

php:
  - 7.1
  - hhvm
  - nightly

matrix:
  fast_finish: true

  allow_failures:
    - php: hhvm
    - php: nightly

services:
  - mysql

before_script:
  # prevent MySQL went away error
  - mysql -u root -e 'SET @@GLOBAL.wait_timeout=28800;'

  # Create a new database and add all priveleges
  - mysql -u root -e "create database IF NOT EXISTS chatter;"

  # Current DIR
  - pwd

  # Move up one directory
  - cd ../

  # Create a New Laravel App
  - composer create-project --prefer-dist laravel/laravel=5.8.* chatter-app

  # CD into the new laravel app
  - cd chatter-app

  # Include Chatter Package & Markdown package
  - composer require "chatter-laravel/core:^5.8"
  - composer dump-autoload

  # Add the database credentials
  - sed 's/DB_DATABASE=homestead/DB_DATABASE=chatter/g' .env > environment
  - sed 's/DB_USERNAME=homestead/DB_USERNAME=root/g' environment > .env
  - sed 's/DB_PASSWORD=secret/DB_PASSWORD=/g' .env > environment
  - rm .env
  - mv environment .env

  # Temponary fix for testing with another charset
  - php -r "file_put_contents('config/database.php', str_replace('utf8mb4', 'utf8', file_get_contents('config/database.php')));"

  # Install chatter
  - php artisan preset chatter -q -n

  # Remove the default phpunit.xml and replace it with chatter phpunit.xml
  - rm phpunit.xml
  - cp vendor/chatter-laravel/core/phpunit.xml phpunit.xml

script:
  - vendor/bin/phpunit
